### ISSUE TITLE
Switching from SwissChannel directly into InGameChannel doesn't reinitialize the session

### ISSUE THREAD

**Issue by Doxylamin** [saltminede/saltychat-docs#1]
Sorry for the previous edits of this issue. We had some fun in TeamSpeak with you ;-)

When switching from a SwissChannel directly into the InGameChannel, Salty Chat won't re-set the Username to the specified TeamSpeakName and/or sync the player with others.

This issue can be reproduced easily by setting at least one SwissChannel, switching to it, and back into the InGame Channel.

**Comment by BlackFlash5** [comment]
The only issue should be, that the client won't be renamed to the instance name.
Will be fixed in the next version.

**Comment by BlackFlash5** [comment]
Was fixed in 0.4.2
