### ISSUE TITLE
[Feature-Request] Possibillity to change Distortion of Voice for NoLoS

### ISSUE THREAD

**Issue by McP4nth3r** [saltminede/saltychat-docs#12]
We use the NoLoS feature for players that sits in a car and would speak with other players outsite of the car.

the Problem is, when the mic Quality of the Player is worst than other the other players cant understand them. When it would be possible to change the distortion  of the muffeling sound we can adjust this a bit down.
The other way would be, we would to implement the NoLoS to motorbike helmets too but this is to heavy for an helmet 

We would be happy if there was an opportunity to implement it :)
Mfg McP4nth3r

**Comment by BlackFlash5** [comment]
`NoLoS` doesn't use a distortion at all, it's a high and low frequency cut.
Making this adjustable would require to replace the `bool` property with e.g. an `int` property to control the range of the frequency cut.
However this would break compatibility with scripts and would require a new major version.
So this is more something for the next major version, with more changes then just this.

**Comment by McP4nth3r** [comment]
ok this sounds nice thanks for the answer

**Comment by BlackFlash5** [comment]
Will be implemented in 2.0.0, currently being tested in version 2.0.0p1.

**Comment by BlackFlash5** [comment]
2.0.0 is with this feature implemented on the stable branch.
