### ISSUE TITLE
[Feature-Request] Implement isAlive state in SelfStateUpdate Command

### ISSUE THREAD

**Issue by MypowerHD** [saltminede/saltychat-docs#16]
Actually when we're not alive, we can hear other peoples, to fix this issue we need an Modification of the "SelfStateUpdate".
Like if we're not alive, the plugin should mute all users in the channel.

the script-side implementation could look like in the Discrod Channel ([link](https://discordapp.com/channels/447371204844847105/660633826472624198/726446579082330173)).

**Comment by BlackFlash5** [comment]
Will be implemented in 2.0.0p2.

**Comment by BlackFlash5** [comment]
2.0.0 is with this feature implemented on the stable branch.
