### ISSUE TITLE
Salty Chat 2.1.0 (3.5.3 Stable) Gamepad Issue - Redm

### ISSUE THREAD

**Issue by JDmyster** [saltminede/saltychat-docs#20]
I am using an Xbox One Controller for Redm, the server I am playing on recently updated to the version of title chat mentioned in this title. 

Using LT to aim, causes the add-on to change talking range. LT is detected as a Z-Axis and I suspect that holding it down, the add-on is mistaking the Axis as the keybind (Z is the key to change voice range). Z still works for changing voice range on the keyboard, this update has an issue where it is detecting the Z-Axis as a secondary input. Is there a command line I can add somewhere to prevent this from happening?

**Comment by BlackFlash5** [comment]
This issue has nothing to do with this repo.
