### ISSUE TITLE
Teamspeak crashes while using Megaphone

### ISSUE THREAD

**Issue by Jan-Moo** [saltminede/saltychat-docs#25]
Teamspeak crashes after 1-2 Seconds when using the Megaphone. Even if you press the Hotkey in a Swiss-Channel

Edit: As long as im not speaking its not crashing. As soon as i start to talk it crashes after 1-2 Seconds. When other Users talk via Megaphone there is no crash either.

Hardware Input is a Yamaha AG03 USB-Mixer (44100 Hz Sample Rate)
Teamspeak Version: 3.5.6
Salty Chat TS Plugin Version: 2.2.2
Salty Chat FiveM Version: Newest (Atleast thats what Admin tells me)
FiveM Build: b2189
FiveM Onesync: Yes
Teamspeak Crashdump: [ts3dump_1615584776116.zip](https://github.com/saltminede/saltychat-docs/files/6133204/ts3dump_1615584776116.zip)

**Comment by BlackFlash5** [comment]
Can you check if this issue is fixed with [2.2.3](https://www.saltmine.de/saltychat/download/2.2.3)?

**Comment by Jan-Moo** [comment]
Yup no more Crashes with 2.2.3. 
The Megaphone does still work in Swiss Channels. But since it isnt crashing anymor its nothing but a tiny inconvenience.

Thanks alot!

**Comment by BlackFlash5** [comment]
> The Megaphone does still work in Swiss Channels.

Fixed in 2.2.4, which is now on the testing branch.
