### ISSUE TITLE
[Native Warning] When Change Voice Range

### ISSUE THREAD

**Issue by gerung** [saltminede/saltychat-docs#26]
Hi, i get the native warning when change the voice range
![image](https://user-images.githubusercontent.com/64629964/111570351-3f05df80-87d7-11eb-8157-20b40ae413f4.png)

Latest Artifact | Latest Saltychat | Plugin v2.2
Thanks

**Comment by BlackFlash5** [comment]
This repo is for Salty Chat and the documentation, not for issues with game modes.
