### ISSUE TITLE
Teamspeak closing or crashing while using Radio or Phone

### ISSUE THREAD

**Issue by Vision-AK** [saltminede/saltychat-docs#30]
So recently i have been facing an issue that whenever someone says something on the radio or phone my ts automatically stops even though it is working fine when i am talking to someone if he is near to me.I even reinstalled ts and plugin but nothing helped me I also even searched it on google but didn't worked.I hope you will look forward to my problem.

Plugin Version: 2.2.5
TeamSpeak version:3.5.6
Salty Chat Fivem Version: Newest
Fivem build: b2060

**Comment by BlackFlash5** [comment]
To debug this issue we need more information, follow the steps bellow:
- Download and install [2.2.6p1](https://www.saltmine.de/saltychat/download/2.2.6p1)
- Enable `ExtensiveDebug`-logging: Plugins > Salty Chat > Open Settings > Enable `Expert Mode` > set `Log Level` to `ExtensiveDebug`
- Talk to someone ingame next to you
- Use the radio/phone, so TS crashes
- Send the crashdump (`%appdata%\TS3Client\crashdumps`), or log (`%appdata%\TS3Client\logs`) if there is no dump

**Comment by Vision-AK** [comment]
> To debug this issue we need more information, follow the steps bellow:
> 
> * Download and install [2.2.6p1](https://www.saltmine.de/saltychat/download/2.2.6p1)
> * Enable `ExtensiveDebug`-logging: Plugins > Salty Chat > Open Settings > Enable `Expert Mode` > set `Log Level` to `ExtensiveDebug`
> * Talk to someone ingame next to you
> * Use the radio/phone, so TS crashes
> * Send the crashdump (`%appdata%\TS3Client\crashdumps`), or log (`%appdata%\TS3Client\logs`) if there is no dump

It says that it doesnt support the file type how can i send you then

**Comment by Vision-AK** [comment]
> To debug this issue we need more information, follow the steps bellow:
> 
> * Download and install [2.2.6p1](https://www.saltmine.de/saltychat/download/2.2.6p1)
> * Enable `ExtensiveDebug`-logging: Plugins > Salty Chat > Open Settings > Enable `Expert Mode` > set `Log Level` to `ExtensiveDebug`
> * Talk to someone ingame next to you
> * Use the radio/phone, so TS crashes
> * Send the crashdump (`%appdata%\TS3Client\crashdumps`), or log (`%appdata%\TS3Client\logs`) if there is no dump

[ts3client_2021-05-01__03_46_32.190638.log](https://github.com/saltminede/saltychat-docs/files/6408429/ts3client_2021-05-01__03_46_32.190638.log)

Here are the log and the picture what happens to ts once someone talks on radio i cannot send the crash dump as it doesnt support the file type and also i used the 2.2.5 version as the version you said isnt accepted by the server i hope that you will fix my issue through these things
![TSCRASH SHOW](https://user-images.githubusercontent.com/83432826/116762114-e14def80-aa32-11eb-9499-23e4fc9ebcc7.png)

**Comment by BlackFlash5** [comment]
`.zip` seems to be supported.
If that's a FiveM server they have to [update](https://github.com/saltminede/saltychat-fivem/commit/48949fa551640de220eed2edf50f06654f87a55e) the script to support preview versions.
You also have to use 2.2.6p1 since `ExtensiveDebug` has way more information to debug this issue.

**Comment by Vision-AK** [comment]
> `.zip` seems to be supported.
> If that's a FiveM server they have to [update](https://github.com/saltminede/saltychat-fivem/commit/48949fa551640de220eed2edf50f06654f87a55e) the script to support preview versions.
> You also have to use 2.2.6p1 since `ExtensiveDebug` has way more information to debug this issue.

[a1969d9d-5b12-415b-83c4-0625d3a78f60.zip](https://github.com/saltminede/saltychat-docs/files/6408877/a1969d9d-5b12-415b-83c4-0625d3a78f60.zip)

So here is the crash dump and the thing is the server i am playing is SVRP and i dont think they will update it for just a single person request if you can do something please look forward to it thanks.

**Comment by BlackFlash5** [comment]
You can install [2.3.0](https://www.saltmine.de/saltychat/download/testing) and follow the [instructions](https://github.com/saltminede/saltychat-docs/issues/30#issuecomment-830193471).

**Comment by BlackFlash5** [comment]
Should be fixed in 2.3.3.
