### ISSUE TITLE
Radio Range

### ISSUE THREAD

**Issue by DanyCryEn** [saltminede/saltychat-docs#31]
Hi, i've one problem with range of radio... because i want more range.... 8 km it's impossible for my server, i think 15 km it's perfect... how i can change this?

**Comment by Hanashi** [comment]
You can use distributed via radio towers.

Look at this picture:
![Radio Modes](https://raw.githubusercontent.com/saltminede/saltychat-docs/master/media/concept-radio-modes.jpg)

**Comment by DanyCryEn** [comment]
How bro?... where i can modify that? it's first time with SaltyChat for me



> You could use distributed via radio towers.
> 
> Look at this picture:
> ![Radio Modes](https://raw.githubusercontent.com/saltminede/saltychat-docs/master/media/concept-radio-modes.jpg)

**Comment by Hanashi** [comment]
You need to define the radio towers and send it to each client with [command 32](https://github.com/saltminede/saltychat-docs/blob/master/commands.md#32--radiotowerupdate). You can find a list of all radio towers [here](https://github.com/DurtyFree/gta-v-data-dumps/blob/master/objectslocations/worldRadioTowers.json).

Than you must modify the `RadioType` on [command 30](https://github.com/saltminede/saltychat-docs/blob/master/commands.md#30--radiocommunicationupdate) on start radio transfer for `SenderRadioType` and `OwnRadioType`. Set it to `12`. This means Long Range + Distributed.

**Comment by DanyCryEn** [comment]
> You need to define the radio towers and send it to each client with [command 32](https://github.com/saltminede/saltychat-docs/blob/master/commands.md#32--radiotowerupdate). You can find a list of all radio towers [here](https://github.com/DurtyFree/gta-v-data-dumps/blob/master/objectslocations/worldRadioTowers.json).
> 
> Than you must modify the `RadioType` on [command 30](https://github.com/saltminede/saltychat-docs/blob/master/commands.md#30--radiocommunicationupdate) on start radio transfer for `SenderRadioType` and `OwnRadioType`. Set it to `12`. This means Long Range + Distributed.

Thanks, but i don't know where i've to put this coords of tower radio... and how set command 32.... have to much files in saltychat... jesus 🗡️  :)

**Comment by DanyCryEn** [comment]
where i've to put command 32?

**Comment by BlackFlash5** [comment]
If you don't know and have a running deployment you are probably just using a script written by somebody.
Obviously this would be the wrong place to ask this in such a case and you should ask in the script's repo.
