### ISSUE TITLE
[Feature-Request] Option to set all sub-channels of a channel as a swisschannel

### ISSUE THREAD

**Issue by DerGonzi** [saltminede/saltychat-docs#35]
Option to set one or more channels as swisschannel including all sub-channels

**Comment by BlackFlash5** [comment]
Implemented in 2.3.4, feedback is appreciated.

**Comment by deluvas1911** [comment]
`2021-06-12 13:20:06.979765|DEBUG   |Salty Chat    |9  |Switched to a swiss channel (Team 1)`
Team 1 is a sub-channel from the id I've set as swiss channel. Looking good

**Comment by BlackFlash5** [comment]
2.3.5 is on stable including this change.
