### ISSUE TITLE
Swiss channel has higher priority then ingame channel

### ISSUE THREAD

**Issue by deluvas1911** [saltminede/saltychat-docs#37]
**Version**
2.3.4 Testing

**Describe the bug**
If you declare the ingame channel also as an swiss channel you won't get moved out of the ingame channel upon disconnect

**To Reproduce**
1. Declare ingame channel also as swiss channel
2. Disconnect from server

**Expected behavior**
The plugin should check on the initialization command if one of the swiss channels is also the ingame channel and then ignore it

**Comment by BlackFlash5** [comment]
2.3.5 will reset the game instance if the ingame channel is also a swiss channel.
Can you confirm if everything is working as expected now?

**Comment by deluvas1911** [comment]
```
2021-06-13 21:45:09.481174|ERROR   |Salty Chat    |9  |Ingame channel can't be a swiss channel
2021-06-13 21:45:09.481675|DEBUG   |Salty Chat    |12 |{"Error":6,"Message":"Ingame channel can't be a swiss channel","ServerIdentifier":"xyz"}
```
Confirmed working. Game instance gets reseted and client doesn't gets moved to the ingame channel
