### ISSUE TITLE
Feature-Request: Don't move user on connect while in SwissChannel

### ISSUE THREAD

**Issue by deluvas1911** [saltminede/saltychat-docs#4]
Is it possible to add (maybe optional) feature to don't move users when they're connecting while they are in a swiss channel?

Would be great, at special during the development stage, while often reconnecting to don't get moved all the time and always rejoin the swiss channel

Greetings

**Comment by BlackFlash5** [comment]
Fixed in 0.5.0, thanks for reporting that.
