### ISSUE TITLE
[ISSUE] Saltamine with CDN not working on AltV

### ISSUE THREAD

**Issue by younesdev123** [saltminede/saltychat-docs#5]
Hi there,

we're setup AltV to provide the server using an CDN.
As soon as people connect to the CDN game server, they don't get moved into the ingame channel.
If we remove the CDN, players get moved to the ingame channel.

I checked the saltmine log file and if we connect through CDN there isn't even the initialize command receiving.

**Comment by BlackFlash5** [comment]
That's most likely an issue with the origin of the websocket connecten.
See `OriginExceptions` @ https://github.com/saltminede/saltychat-docs#configuration-file for more info.
