### ISSUE TITLE
[Feature-Request] Voice effect for a megaphone

### ISSUE THREAD

**Issue by younesdev123** [saltminede/saltychat-docs#6]
The possibility that when we are in a police vehicle with the sirens activated, and that when we speak there is a megaphone effect

**Comment by BlackFlash5** [comment]
Implemented in 1.1.0, please test the feature and provide some feedback.
https://github.com/saltminede/saltychat-docs/blob/1.x.x/commands.md#16--megaphonecommunicationupdate

**Comment by BlackFlash5** [comment]
Since there was no real feedback > closed
