### ISSUE TITLE
[Feature-Request] Possibility of having an echo effect

### ISSUE THREAD

**Issue by younesdev123** [saltminede/saltychat-docs#7]
I open this request in order to have an echo system, which will allow to develop the echo in tunnels for example.

**Comment by BlackFlash5** [comment]
Implemented in 1.0.0 DP2, please test the feature and provide some feedback.
https://github.com/saltminede/saltychat-docs/blob/1.x.x/commands.md#4--selfstateupdate

**Comment by BlackFlash5** [comment]
Since there was no real feedback > closed
